docanalyser/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.custom_login, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

docanalyser/docanalyser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = ([
    path('', include('upload.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('metrics/', include('django_prometheus.urls')),
])

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docanalyser/upload/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.upload_document, name='upload'),
    path('document/<int:doc_id>/', views.document_detail, name='document_detail'),
    path('document/analyse/<int:doc_id>/', views.document_analyse, name='document_analyse'),
    path('delete_document/', views.delete_document_view, name='delete_document'),
    path('get_text/<int:doc_id>/', views.get_text, name='get_text'),
]

docanalyser/upload/models.py
from django.db import models
from django.contrib.auth.models import User

class Docs(models.Model):
    file_path = models.CharField(max_length=200)
    size = models.IntegerField()

class UsersToDocs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_docs')
    document = models.ForeignKey(Docs, on_delete=models.CASCADE, related_name='doc_users')

    class Meta:
        unique_together = ('user', 'document')

class Price(models.Model):
    file_type = models.CharField(max_length=100)
    price = models.FloatField()

class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    docs_id = models.ForeignKey(Docs, on_delete=models.CASCADE)
    order_price = models.FloatField()
    payment = models.BooleanField(default=False)

docanalyser/upload/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UploadFileForm(forms.Form):
    file = forms.FileField()

from django import forms

class DeleteDocumentForm(forms.Form):
    document_id = forms.IntegerField(
        label='ID документа для удаления',
        min_value=1,
        widget=forms.NumberInput(attrs={'class': 'form-control'}))

docanalyser/upload/views.py
import base64
import json

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.core.files.storage import default_storage

from django.shortcuts import render, redirect

from .api_client import call_fastapi
from .models import Docs, UsersToDocs
from .forms import UploadFileForm, DeleteDocumentForm


def home(request):
    documents = Docs.objects.all()  # Получаем все загруженные картинки
    return render(request, 'upload/home.html', {'documents': documents, 'request': request})


@login_required
def upload_document(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['file']

            file_name = default_storage.save(uploaded_file.name, uploaded_file)
            file_path = uploaded_file.name
            file_size = uploaded_file.size

            uploaded_file.seek(0)
            with open(f'media/{file_path}', "rb") as image_file:
                image_base64 = base64.b64encode(image_file.read()).decode('utf-8')


            # Сохраняем информацию в базу данных
            doc = Docs.objects.create(
                file_path=file_path,
                size=file_size
            )

            UsersToDocs.objects.create(
                user=request.user,
                document=doc
            )

            api_response = call_fastapi(
                'documents/upload_doc',
                method='post',
                data={
                    "id": doc.pk,
                    "image_base64": image_base64
                },
            )

            if not api_response:
                messages.error(request, 'Ошибка обработки документа')
                print('ERROR')
                return redirect('home')

            print("API Response:", api_response)

            return redirect('home')
    else:
        form = UploadFileForm()
    return render(request, 'upload/upload.html', {'form': form})


def is_moderator(user):
    return user.groups.filter(name='Moderators').exists() or user.is_superuser


@user_passes_test(is_moderator)
def delete_document_view(request):
    if request.method == 'POST':
        form = DeleteDocumentForm(request.POST)
        if form.is_valid():
            doc_id = form.cleaned_data['document_id']
            try:
                doc = Docs.objects.get(id=doc_id)
                doc.delete()
                messages.success(request, f'Документ {doc_id} успешно удален')

                api_response = call_fastapi(
                    f'documents/doc_delete/{doc_id}',
                    method='delete',
                )

                if not api_response:
                    messages.error(request, 'Ошибка обработки документа')
                    print('ERROR')
                    return redirect('home')

                print("API Response:", api_response)

                return redirect('delete_document')
            except Docs.DoesNotExist:
                messages.error(request, f'Документ с ID {doc_id} не найден')
    else:
        form = DeleteDocumentForm()

    return render(request, 'upload/delete_document.html', {'form': form})


@login_required
def document_detail(request, doc_id):
    try:
        user_doc = UsersToDocs.objects.get(user=request.user, doc_id=doc_id)
        doc = user_doc.doc
        return render(request, 'upload/document.html', {'doc': doc})
    except UsersToDocs.DoesNotExist:
        raise Http404("Документ не найден или у вас нет доступа")


@login_required
def document_analyse(request, doc_id):
    if request.method == 'GET':
        api_response = call_fastapi(
            f'documents_text/doc_analyse/{doc_id}',
            method='get',
            data={
                "id": doc_id
            },
        )

        if not api_response:
            messages.error(request, 'Ошибка обработки документа')
            print('ERROR')
            return redirect('home')

        print("API Response:", api_response)

    return render(request, 'upload/document_analyse.html')


@login_required
def get_text(request, doc_id):
    if request.method == 'GET':
        api_response = call_fastapi(
            f'documents_text/get_text/{doc_id}',
            method='get',
            data={
                "id": doc_id
            },
        )

        context = {
            'doc_id': doc_id,
            'api_response': api_response
        }

        if not api_response:
            print('ERROR')
            messages.error(request, f"Ошибка при получении текста")
            return render(request, 'upload/get_text.html')

        print("API Response:", api_response)

        # Если статус 202 - успешно
        messages.success(request, f'Текст документа: {api_response["message"]}')
        return render(request, 'upload/get_text.html', context)
    return render(request, 'upload/get_text.html')

docanalyser/templates/upload/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Анализатор картинок</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Главная страница</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'upload' %}">Добавить</a>
                </li>
            </ul>
            <div class="auth-buttons">
                {% if user.is_authenticated %}
                    <span>Привет, {{ user.username }}!</span>
                    <a href="{% url 'accounts:logout' %}">
                        <button>Выйти</button>
                    </a>
                {% else %}
                    <a href="{% url 'accounts:login' %}">
                        <button>Войти</button>
                    </a>
                    <a href="{% url 'accounts:register' %}">
                        <button>Регистрация</button>
                    </a>
                {% endif %}
                </a>
            </div>
        </div>
    </div>
</nav>


<div style="padding-top: 60px;" class="container">
    {% block content %} {% endblock %}
</div>


</body>
</html>

docanalyser/templates/upload/delete_document.html
{% extends "upload/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Удаление документа</h2>
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form>

            {% if messages %}
            <div class="mt-3">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

docanalyser/templates/upload/document_analyse.html
{% extends 'upload/base.html' %}

{% block title %}
Анализирую...
{% endblock %}

{% block content %}
<h1>Анализирую...</h1>
<h6>Посмотреть результат можно, нажав на кнопку на главной странице</h6>
<a href="{% url 'home' %}">
    <button>На главную</button>
</a>

{% endblock %}

docanalyser/templates/upload/get_text.html
{% extends 'upload/base.html' %}

{% block title %}Получить текст{% endblock %}

{% block content %}
<div class="container">
    <h1>Текст документа #{{ doc_id }}</h1>

    <!-- Вывод сообщений об ошибках/успехе -->
    {% if messages %}
    <div class="mt-3">
        {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Вывод текста документа, если есть -->
    {% if api_response.status_code == 202 and api_response.text %}
    <div class="mt-4 p-3 border rounded bg-light">
        <h3>Текст документа:</h3>
        <pre>{{ api_response.text }}</pre>
    </div>
    {% endif %}



    <div class="mt-4">
        <a href="{% url 'home' %}" class="btn btn-primary">На главную</a>
    </div>
</div>
{% endblock %}

docanalyser/templates/upload/home.html
{% extends 'upload/base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block content %}
<div class="image-grid">
    {% for relation in request.user.user_docs.all %}
    <div class="image-item">
        <p>ID: {{ relation.document.id }}</p>
        <p>Размер: {{ relation.document.size }} байт</p>
        <img src="{{ MEDIA_URL }}{{ relation.document.file_path }}" alt="Документ" width="200">
        <a href="{% url 'document_analyse' relation.document.id %}" class="btn btn-primary">Проанализировать</a>
        <a href="{% url 'get_text' relation.document.id %}" class="btn btn-primary">Посмотреть текст</a>
    </div>
    {% empty %}
    <p>Вы еще не загружали документы</p>
    {% endfor %}
</div>
{% endblock %}

docanalyser/templates/upload/upload.html
{% extends 'upload/base.html' %}

{% block title %}
Загрузить картинку
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Загрузить</button>
    </form>
    <br>
    <a href="{% url 'home' %}" class="btn btn-primary">На главную</a>
{% endblock %}